//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyLogInSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bank
    {
        public decimal AccountNumber { get; set; }
        public string AadharNo { get; set; }
        public Nullable<double> Balence { get; set; }
        public string PhoneNumber { get; set; }
    
        public virtual LogInCdt LogInCdt { get; set; }
    }
}
